global using SandboxMenu.Domain.Persistence;
global using SandboxMenu.Domain.Prefabs;
global using SandboxMenu.Settings;
global using SandboxMenu.UI;
global using SandboxMenu.UI.Framework;
global using SandboxMenu.UI.ViewModels;
global using UiFramework;
global using UiFramework.Data;
global using UiFramework.Styling;
